---

- hosts: all
  vars_prompt:
    - name: username
      prompt: "Please provide the username"
      private: false
    - name: first_time_setup
      prompt: "Perform first time setup (yes/NO)?"
      private: no
      default: no
  roles:
    - role: install
    - role: config
