- name: Install packages via apt (this may take a while)
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - audacity
      - cheese
      - conky
      - dbus-x11
      - dconf-cli
      - dconf-editor
      - distrobox
      - drawing
      - evince
      - flatpak
      - firefox-esr
      - git
      - gnome-system-monitor
      - gnome-power-manager
      - gparted
      - gufw
      - htop
      - jq
      - libglib2.0-dev
      - lrzip
      - obs-studio
      - openjdk-17-jdk
      - pipx
      - psmisc
      - python3-pip
      - python3-virtualenv
      - remmina
      - samba
      - terminator
      - timeshift
      - tlp
      - tmux
      - transmission-gtk
      - ufw
      - vim
      - virt-manager
      - vlc
      - wireguard
      - wireshark
      - xfce4-whiskermenu-plugin
