- name: 'apt: Upgrade all packages'
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_upgrade

- name: 'apt: Install packages (this may take a while)'
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - apt-transport-https
      - audacity
      - autotools-dev
      - blueman
      - catfish
      - ca-certificates
      - cheese
      - cloud-init
      - cmake
      - command-not-found
      - conky
      - curl
      - dbus-x11
      - dconf-cli
      - dconf-editor
      - debhelper
      - dh-virtualenv
      - distrobox
      - drawing
      - evince
      - flatpak
      - galculator
      - gdebi
      - git
      - gnome-disk-utility
      - gnome-power-manager
      - gnome-system-monitor
      - gnome-system-tools
      - gnupg
      - gparted
      - graphicsmagick-imagemagick-compat
      - gufw
      - handbrake
      - htop
      - ipython3
      - iotop
      - jq
      - kdeconnect
      - libffi-dev
      - libglib2.0-dev
      - libncurses5-dev
      - libpcap-dev
      - libreadline-dev
      - linux-perf
      - lrzip
      - menulibre
      - mp3wrap
      - net-tools
      - nfs-common
      - obs-studio
      - openjdk-17-jdk
      - original-awk
      - piper
      - pipx
      - psmisc
      - python3-pip
      - python3-setuptools
      - python3-virtualenv
      - qimgv
      - remmina
      - samba
      - software-properties-common
      - sshfs
      - sshpass
      - strace
      - stress
      - tcpdump
      - terminator
      - timeshift
      - tlp
      - tmux
      - transmission-gtk
      - ufw
      - unrar-free
      - vim
      - virt-manager
      - vlc
      - wireguard
      - wireshark
      - xdemineur
      - xfce4-whiskermenu-plugin
      - xournal
      - xsel
      - zip
  register: apt_install

- name: 'command-not-found: Update packages'
  shell: update-command-not-found
  when: apt_upgrade.changed or apt_install.changed
