- name: 'argo-cd: Download executable'
  get_url:
    url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    dest: "/usr/local/bin/argocd"
    mode: '755'
  tags: argocd

- name: 'argocd: Add autocomplete'
  become: true
  become_user: "{{ username }}"
  shell: /usr/local/bin/argocd completion bash > /home/{{ username }}/.bash_autocomplete/argocd
  tags: k3d
