- name: Create folders
  become: true
  become_user: "{{ username }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - '/home/{{ username }}/dev'
    - '/home/{{ username }}/Programs/distrobox/debian-home'
    - '/home/{{ username }}/Programs/distrobox/fedora-home'
    - '/home/{{ username }}/Programs/distrobox/opensuse-home'
    - '/home/{{ username }}/Programs/distrobox/ubuntu-home'
    - '/home/{{ username }}/Programs/joplin'
    - '/home/{{ username }}/Programs/ladder'
    - '/home/{{ username }}/Programs/shortcuts'
    - '/home/{{ username }}/Programs/tgpt'
    - '/home/{{ username }}/.local/share/applications'
    - '/home/{{ username }}/.ssh'
    - '/home/{{ username }}/.config/autostart'
    - '/home/{{ username }}/.config/gtk-3.0'
    - '/home/{{ username }}/.config/terminator'

- name: Delete unused default folders
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - '/home/{{ username }}/Music'
    - '/home/{{ username }}/Public'
    - '/home/{{ username }}/Templates'
    - '/home/{{ username }}/Videos'
