- name: Create regular folders
  become_user: "{{ username }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - '/home/{{ username }}/dev'
    - '/home/{{ username }}/Programs'
    - '/home/{{ username }}/Programs/shortcuts'
    - '/home/{{ username }}/.local/share/applications'
    - '/home/{{ username }}/.ssh'
    - '/home/{{ username }}/.config/autostart'
    - '/home/{{ username }}/.config/gtk-3.0'

- name: Delete unused default folders
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - '/home/{{ username }}/Music'
    - '/home/{{ username }}/Public'
    - '/home/{{ username }}/Templates'
    - '/home/{{ username }}/Videos'
