- name: 'preinstall: Create folders'
  become: true
  become_user: "{{ username }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - '/home/{{ username }}/.bash_autocomplete'
    - '/home/{{ username }}/.config/rclone'
    - '/home/{{ username }}/.kube'
    - '/home/{{ username }}/dev'
    - '/home/{{ username }}/gdrive'
    - '/home/{{ username }}/Programs/distrobox/debian-home'
    - '/home/{{ username }}/Programs/distrobox/fedora-home'
    - '/home/{{ username }}/Programs/distrobox/opensuse-home'
    - '/home/{{ username }}/Programs/distrobox/ubuntu-home'
    - '/home/{{ username }}/Programs/rclone/log'
    - '/home/{{ username }}/Programs/shortcuts'
    - '/home/{{ username }}/.local/share/applications'
    - '/home/{{ username }}/.local/share/ice/firefox/whatsapp'
    - '/home/{{ username }}/.ssh'
    - '/home/{{ username }}/.config/autostart'
    - '/home/{{ username }}/.config/gtk-3.0'
    - '/home/{{ username }}/.config/k9s/skins'
    - '/home/{{ username }}/.config/terminator'

- name: 'preinstall: Create folders (root)'
  file:
    path: "{{ item }}"
    state: directory
    owner: 'root'
    group: 'root'
    mode: '755'
  loop:
    - '/opt/joplin'
    - '/opt/micromamba'
    - '/opt/ydiff'

- name: 'preinstall: Delete unused default folders'
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - '/home/{{ username }}/Music'
    - '/home/{{ username }}/Public'
    - '/home/{{ username }}/Templates'
    - '/home/{{ username }}/Videos'
