- name: Add repo key for docker
  shell: |
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

- name: Copy docker source to /etc/apt/sources.list.d (template)
  template:
    src: sources-list/docker.list.j2
    dest: "/etc/apt/sources.list.d/docker.list"
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Install docker packages
  apt:
    update_cache: true
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add user "{{ username }}" to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: true
  when: ansible_facts.services['docker.service'] is undefined

- name: Disable docker service
  service:
    name: docker
    enabled: false
    state: stopped
