- name: Add gpg key for docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
  tags: docker

- name: Add repo for docker
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian   {{ ansible_lsb.codename }} stable"
    filename: docker
    state: present
  tags: docker

- name: Install docker packages
  apt:
    update_cache: true
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  tags: docker

- name: Add user "{{ username }}" to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: true
  when: ansible_facts.services['docker.service'] is undefined
  tags: docker

- name: Disable docker service
  service:
    name: docker
    enabled: false
    state: stopped
  tags: docker
