- name: Add gpg key for firefox
  apt_key:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg
    keyring: /etc/apt/trusted.gpg.d/firefox.gpg

- name: Add repo for firefox
  apt_repository:
    repo: "deb https://packages.mozilla.org/apt mozilla main"
    filename: mozilla
    state: present

- name: Install firefox package
  apt:
    update_cache: true
    name: firefox
    state: latest
