- name: Clone fzf
  git:
    repo: "https://github.com/matuzalemmuller/fzf"
    dest: "/opt/fzf"
    force: yes
  tags: fzf

- name: "Install and configure fzf (root)"
  shell: /opt/fzf/install --key-bindings --completion --update-rc
  tags: fzf

- name: "Install and configure fzf ({{ username }})"
  become: true
  become_user: "{{ username }}"
  shell: /opt/fzf/install --key-bindings --completion --update-rc
  tags: fzf
