- name: Clone hstr
  git:
    repo: "https://github.com/matuzalemmuller/hstr"
    dest: "/tmp/hstr"
    force: yes

- name: Configure hstr
  shell: |
    cd ./build/tarball
    ./tarball-automake.sh
    cd ../..
    ./configure
  args:
    chdir: "/tmp/hstr"

- name: Delete previous hstr binaries because the makefile is not smart
  file:
    path: "{{ item.path }}"
    state: absent
  loop:
    - path: "/usr/local/bin/hh"
    - path: "/usr/loca/bin/hstr"

- name: Install hstr
  make:
    chdir: "/tmp/hstr"
    target: install

- name: Delete hstr folder
  file:
    path: "/tmp/hstr"
    state: absent
