- name: Install kind
  shell: |
    [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
    chmod +x ./kind
    sudo mv ./kind /usr/local/bin/kind

- name: Add kind auto-completion to .bashrc
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Add kind autocomplete"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      source <(kind completion bash)
