- name: 'kind: Download executable'
  get_url:
    url: https://github.com/kubernetes-sigs/kind/releases/latest/download/kind-linux-amd64
    dest: "/usr/local/bin/kind"
    mode: '755'
  tags: kind

- name: 'kind: Add autocomplete'
  become: true
  become_user: "{{ username }}"
  shell: /usr/local/bin/kind completion bash > /home/{{ username }}/.bash_autocomplete/kind
  tags: kind
