- import_tasks: create-folders.yml
- import_tasks: apt.yml
- import_tasks: discord.yml
- import_tasks: first_time_install.yml
  when: first_time_setup | bool
- import_tasks: flatpak.yml
- import_tasks: hcloud-manager.yml
- import_tasks: joplin.yml
- import_tasks: kind.yml
- import_tasks: macbook.yml
  when: ansible_product_name is match("MacBookPro12,1")
- import_tasks: tgpt.yml
- import_tasks: vim-gitgutter.yml
- import_tasks: remove-unused.yml
