- name: 'rclone: Get release info'
  uri:
    url: https://api.github.com/repos/rclone/rclone/releases/latest
    return_content: yes
  register: rclone_latest_release
  tags: rclone

- name: 'rclone: Convert release from raw to ansible fact'
  set_fact:
    rclone_latest_release_json: "{{ rclone_latest_release.content | from_json }}"
  tags: rclone

- name: 'rclone: Install web .deb'
  apt:
    deb: https://github.com/rclone/rclone/releases/latest/download/rclone-{{ rclone_latest_release_json.tag_name }}-linux-amd64.deb 
  tags: rclone
