- name: 'apt: Remove unused packages'
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - exfalso
      - firefox-esr
      - parole
      - speech-dispatcher
      - xterm

- name: 'apt: Autoremove packages that are no longer required'
  apt:
    autoremove: true
