- name: Remove unused packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - exfalso
      - firefox-esr
      - parole
      - xterm

- name: Autoremove packages that are no longer required
  apt:
    autoremove: true
