- name: Add gpg key for hashicorp repo
  shell: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

- name: Copy hashicorp source to /etc/apt/sources.list.d (template)
  template:
    src: sources-list/hashicorp.list.j2
    dest: "/etc/apt/sources.list.d/hashicorp.list"
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Install terraform package
  apt:
    update_cache: true
    name: terraform
    state: latest
