- name: 'bashrc: Disable console freeze'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Disable console freeze"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      # disable tmux freeze + ssh fix: https://stackoverflow.com/questions/24623021/getting-stty-standard-input-inappropriate-ioctl-for-device-when-using-scp-thro
      [[ $- == *i* ]] && /usr/bin/stty -ixon

- name: 'bashrc: Add /usr/sbin to PATH'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Add /usr/sbin to PATH"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      export PATH="$PATH:/usr/sbin"

- name: 'bashrc: Add ls aliases'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Add ls aliases"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      alias la='ls -la'
      alias ll='ls -lh'

- name: 'bashrc: Add various aliases'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Add various aliases"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      alias cpv='rsync -ah --info=progress2'
      alias grep='grep --color=auto'
      alias nettop='sudo /usr/local/bin/nettop'
      alias virsh='sudo virsh'
      alias cnf='command-not-found'
      alias usb-transfer-status='watch grep -e Dirty: -e Writeback: /proc/meminfo'
      alias proxmox='ssh root@10.0.0.200'
      alias hetzner='ssh root@10.8.0.2'
      alias serve_folder='python3 -m http.server 8080 --bind 0.0.0.0 --directory '
      alias hssh='ssh -i ~/.ssh/homelab -o StrictHostKeyChecking=no '
      alias watch='watch ' # allows using watch with aliases - https://unix.stackexchange.com/a/25329
      alias kuberemote_source='export KUBECONFIG=/home/{{ username }}/.kube/remoteconfig.yaml'

- name: 'bashrc: Add terraform auto-completion'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Add terraform autocomplete"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      complete -C /usr/bin/terraform terraform

- name: 'bashrc: Add k3d aliases'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Add k3d autocomplete"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      alias k3d-create-cluster='k3d cluster create mycluster --agents 1 -p "30000-30050:30000-30050@loadbalancer"'
      alias k3d-stop-cluster='k3d cluster stop mycluster'
      alias k3d-start-cluster='k3d cluster start mycluster'

- name: 'bashrc: Add kind aliases'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Add kind autocomplete"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      alias kind-create-cluster-full="kind create cluster --config /home/{{ username }}/.kube/kind-cluster-config-full.yaml"
      alias kind-create-cluster-quick="kind create cluster --config /home/{{ username }}/.kube/kind-cluster-config-quick.yaml"

- name: 'bashrc: Source autocompletion'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} bashrc: Source autocompletion"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      for fl in `find /home/matuzalem/.bash_autocomplete/*`; do source $fl; done

- name: 'bashrc: Alias k to kubecolor'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Add kubectl autocomplete"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      alias k=kubecolor
      complete -o default -F __start_kubectl k

- name: 'bashrc: Add qfc sourcing'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Add qfc sourcing"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      [[ -s "$HOME/.qfc/bin/qfc.sh" ]] && source "$HOME/.qfc/bin/qfc.sh"

- name: 'bashrc: Increase default bash history (HISTFILESIZE)'
  lineinfile:
    path: "/home/{{ username }}/.bashrc"
    regexp: '^HISTFILESIZE='
    line: 'HISTFILESIZE=10000'

- name: 'bashrc: Use ydiff for git diff and difftool for individual files'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Replace git diff"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      git() {
        if [ "$1" == "diff" ];  then
            if [ "$#" -eq 1 ]; then
                /opt/ydiff/ydiff.py
            else
                /usr/bin/git difftool --tool=vimdiff -y $2
            fi
        else
            /usr/bin/git "$@"
        fi
      }

- name: 'bashrc: Add micromamba prefix'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Micromamba prefix"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      # >>> mamba initialize >>>
      # !! Contents within this block are managed by 'micromamba shell init' !!
      export MAMBA_EXE='/opt/micromamba/bin/micromamba';
      export MAMBA_ROOT_PREFIX='/home/matuzalem/micromamba';
      __mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
      if [ $? -eq 0 ]; then
          eval "$__mamba_setup"
      else
          alias micromamba="$MAMBA_EXE"  # Fallback on help from micromamba activate
      fi
      unset __mamba_setup
      # <<< mamba initialize <<<

- name: 'bashrc: k8s cheat sheet/helpers'
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} k8s cheat sheet"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      function kcheat() {
      cat << EOF
      # get all pods running in a node
      k get pod -A -o wide --field-selector spec.nodeName=NODE_NAME
      EOF
      }
      function kns() {
        if [[ -z "$1" ]]; then
          kubectl get ns
        else
          kubectl config set-context --current --namespace "$1"
        fi
      }
