- name: Killall xfce4-panel
  shell: killall xfce4-panel

- name: Remove panel folder
  file:
    state: absent
    path: "/home/{{ username }}/.config/xfce4/panel"

- name: Copy config files (first time install)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - src: conky.desktop
      dest: "/home/{{ username }}/.config/autostart"
    - src: disable-xfce-beep.desktop
      dest: "/home/{{ username }}/.config/autostart"
    - src: discord.desktop
      dest: "/home/{{ username }}/.local/share/applications/menulibre-discord.desktop"
    - src: inputrc
      dest: "/home/{{ username }}/.inputrc"
    - src: joplin.desktop
      dest: "/home/{{ username }}/.local/share/applications/joplin.desktop"
    - src: mimeapps.list
      dest: "/home/{{ username }}/.config/mimeapps.list"
    - src: panel
      dest: "/home/{{ username }}/.config/xfce4"
    - src: terminator-default-terminal.rc
      dest: "/home/{{ username }}/.config/xfce4/helpers.rc"
    - src: TODO.txt
      dest: "/home/{{ username }}/Desktop"
    - src: xfce4-panel.xml
      dest: "/home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"

- name: Copy config files (templates)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - src: ssh-config.j2
      dest: "/home/{{ username }}/.ssh/config"
    - src: thunar-bookmarks.j2
      dest: "/home/{{ username }}/.config/gtk-3.0/bookmarks"
    - src: webapp-WhatsappWeb.desktop.j2
      dest: "/home/{{ username }}/.local/share/applications/webapp-WhatsappWeb3834.desktop"
    - src: xfce4-keyboard-shortcuts.xml.j2
      dest: "/home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
 
- name: Copy scripts (templates)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop:
    - src: distrobox_create.sh.j2
      dest: "/home/{{ username }}/Programs/distrobox/distrobox_create.sh"
    - src: screenshot.sh.j2
      dest: "/home/{{ username }}/Programs/shortcuts/screenshot.sh"

- name: Copy config files (root)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: true
  loop:
    - src: conky.conf
      dest: /etc/conky/conky.conf
    - src: xfce4-panel.xml
      dest: /etc/xdg/xfce4/panel/default.xml

- name: Copy config files (templates)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - src: sudoers/nettop
      dest: "/etc/sudoers.d/nettop"
