- name: Copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - src: terminator
      dest: "/home/{{ username }}/.config/terminator"
    - src: tmux.conf
      dest: "/home/{{ username }}/.tmux.conf"
    - src: vimrc
      dest: "/home/{{ username }}/.vimrc"
    - src: webapp-WhatsappWeb.desktop
      dest: "/home/{{ username }}/.local/share/applications/webapp-WhatsappWeb7804.desktop"
    - src: TODO.txt
      dest: "/home/{{ username }}/Desktop"
    - src: discord.desktop
      dest: "/home/{{ username }}/.local/share/applications/menulibre-discord.desktop"
    - src: thunar-bookmarks
      dest: "/home/{{ username}}/.config/gtk-3.0/bookmarks"
    - src: ssh-config
      dest: "/home/{{ username }}/.ssh/config"

- name: Copy conky.conf
  copy:
    src: conky.conf
    dest: /etc/conky/conky.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
