- name: Copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - src: terminator
      dest: "/home/{{ username }}/.config/terminator"
    - src: tmux.conf
      dest: "/home/{{ username }}/.tmux.conf"
    - src: vimrc
      dest: "/home/{{ username }}/.vimrc"
    - src: webapp-WhatsappWeb.desktop
      dest: "/home/{{ username }}/.local/share/applications/webapp-WhatsappWeb7804.desktop"
    - src: TODO.txt
      dest: "/home/{{ username }}/Desktop"
    - src: discord.desktop
      dest: "/home/{{ username }}/.local/share/applications/menulibre-discord.desktop"
    - src: ssh-config
      dest: "/home/{{ username }}/.ssh/config"
    - src: conky.desktop
      dest: "/home/{{ username }}/.config/autostart"
    - src: thunar-bookmarks
      dest: "/home/{{ username }}/.config/gtk-3.0/bookmarks"
    - src: terminator-default-terminal.rc
      dest: "/home/{{ username }}/.config/xfce4/helpers.rc"
    - src: xfce4-keyboard-shortcuts.xml
      dest: "/home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"

- name: Copy config files (executable)
  copy:
    src: screenshot.sh
    dest: "/home/{{ username }}/Programs/shortcuts"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Copy conky.conf
  copy:
    src: conky.conf
    dest: /etc/conky/conky.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
