- name: Copy config files (always)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - src: k9s/config.yaml
      dest: "/home/{{ username }}/.config/k9s/config.yaml"
    - src: k9s/skin-gruvbox-dark.yaml
      dest: "/home/{{ username }}/.config/k9s/skins/gruvbox-dark.yaml"
    - src: kube/kind-cluster-config.yaml
      dest: "/home/{{ username }}/.kube/kind-cluster-config.yaml"
    - src: vscode/snippets/
      dest: "/home/{{ username }}/.config/Code/User/snippets/"
    - src: vscode/settings.json
      dest: "/home/{{ username }}/.config/Code/User/settings.json"
    - src: vscode/keybindings.json
      dest: "/home/{{ username }}/.config/Code/User/keybindings.json"
    - src: terminator
      dest: "/home/{{ username }}/.config/terminator/config"
    - src: tmux.conf
      dest: "/home/{{ username }}/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/debian-home/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/fedora-home/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/opensuse-home/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/ubuntu-home/.tmux.conf"
    - src: vimrc
      dest: "/home/{{ username }}/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/debian-home/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/fedora-home/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/opensuse-home/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/ubuntu-home/.vimrc"
