- name: 'copy-always: Copy config files'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - src: autostart/
      dest: "/home/{{ username }}/.config/autostart/"
    - src: gnome-power-manager.desktop
      dest: "/home/{{ username }}/.local/share/applications/gnome-power-manager.desktop"
    - src: joplin.desktop
      dest: "/home/{{ username }}/.local/share/applications/joplin.desktop"
    - src: kube/k9s-config.yaml
      dest: "/home/{{ username }}/.config/k9s/config.yaml"
    - src: kube/k9s-skin-gruvbox-dark.yaml
      dest: "/home/{{ username }}/.config/k9s/skins/gruvbox-dark.yaml"
    - src: kube/kind-cluster-config.yaml
      dest: "/home/{{ username }}/.kube/kind-cluster-config-quick.yaml"
    - src: kube/kubectl_aliases.sh
      dest: "/home/{{ username }}/.bash_autocomplete/kubectl_aliases.sh"
    - src: mimeapps.list
      dest: "/home/{{ username }}/.config/mimeapps.list"
    - src: vscode/snippets/
      dest: "/home/{{ username }}/.config/Code/User/snippets/"
    - src: vscode/settings.json
      dest: "/home/{{ username }}/.config/Code/User/settings.json"
    - src: vscode/keybindings.json
      dest: "/home/{{ username }}/.config/Code/User/keybindings.json"
    - src: terminator
      dest: "/home/{{ username }}/.config/terminator/config"
    - src: tmux.conf
      dest: "/home/{{ username }}/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/debian-home/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/fedora-home/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/opensuse-home/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/ubuntu-home/.tmux.conf"
    - src: vimrc
      dest: "/home/{{ username }}/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/debian-home/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/fedora-home/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/opensuse-home/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/ubuntu-home/.vimrc"
    - src: xfce4-terminal-config-terminalrc
      dest: "/home/{{ username }}/.config/xfce4/terminal/terminalrc"

- name: 'copy-always: Copy config files (templates)'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - src: thunar-bookmarks.j2
      dest: "/home/{{ username }}/.config/gtk-3.0/bookmarks"
    - src: webapp-WhatsappWeb.desktop.j2
      dest: "/home/{{ username }}/.local/share/applications/webapp-WhatsappWeb3834.desktop"
    - src: xfce4-keyboard-shortcuts.xml.j2
      dest: "/home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"

- name: 'copy-always: Copy config files (root / templates)'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - src: sudoers/amd-pstate
      dest: "/etc/sudoers.d/amd-pstate"
    - src: sudoers/iotop
      dest: "/etc/sudoers.d/iotop"
    - src: sudoers/nettop
      dest: "/etc/sudoers.d/nettop"
    - src: sudoers/virsh
      dest: "/etc/sudoers.d/virsh"

- name: 'copy-always: Copy kube remote conf (proxied kube)'
  copy:
    src: kube/remoteconfig.yaml
    dest: "/home/{{ username }}/.kube/remoteconfig.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0600'
