- name: Killall xfce4-panel
  shell: killall xfce4-panel

- name: Remove panel folder
  file:
    state: absent
    path: "/home/{{ username }}/.config/xfce4/panel"

- name: Copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - src: conky.desktop
      dest: "/home/{{ username }}/.config/autostart"
    - src: disable-xfce-beep.desktop
      dest: "/home/{{ username }}/.config/autostart"
    - src: ladder_ruleset.yml
      dest: "/home/{{ username }}/Programs/ladder/ruleset.yml"
    - src: panel
      dest: "/home/{{ username }}/.config/xfce4"
    - src: vscode-settings.json
      dest: "/home/{{ username }}/.config/Code/User/settings.json"
    - src: vscode-keybindings.json
      dest: "/home/{{ username }}/.config/Code/User/keybindings.json"
    - src: terminator
      dest: "/home/{{ username }}/.config/terminator/config"
    - src: terminator-default-terminal.rc
      dest: "/home/{{ username }}/.config/xfce4/helpers.rc"
    - src: tmux.conf
      dest: "/home/{{ username }}/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/debian-home/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/fedora-home/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/opensuse-home/.tmux.conf"
    - src: tmux.conf
      dest: "/home/{{ username }}/Programs/distrobox/ubuntu-home/.tmux.conf"
    - src: TODO.txt
      dest: "/home/{{ username }}/Desktop"
    - src: vimrc
      dest: "/home/{{ username }}/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/debian-home/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/fedora-home/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/opensuse-home/.vimrc"
    - src: vimrc
      dest: "/home/{{ username }}/Programs/distrobox/ubuntu-home/.vimrc"
    - src: xfce4-panel.xml
      dest: "/home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"

- name: Copy config files (templates)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - src: discord.desktop.j2
      dest: "/home/{{ username }}/.local/share/applications/menulibre-discord.desktop"
    - src: ssh-config.j2
      dest: "/home/{{ username }}/.ssh/config"
    - src: thunar-bookmarks.j2
      dest: "/home/{{ username }}/.config/gtk-3.0/bookmarks"
    - src: webapp-WhatsappWeb.desktop.j2
      dest: "/home/{{ username }}/.local/share/applications/webapp-WhatsappWeb7804.desktop"
    - src: xfce4-keyboard-shortcuts.xml.j2
      dest: "/home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    - src: ladder_systray.desktop.j2
      dest: "/home/{{ username }}/.config/autostart/ladder_systray.desktop"
 
- name: Copy scripts (templates)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop:
    - src: distrobox_create.sh.j2
      dest: "/home/{{ username }}/Programs/distrobox/distrobox_create.sh"
    - src: screenshot.sh.j2
      dest: "/home/{{ username }}/Programs/shortcuts/screenshot.sh"
    - src: ladder_start.sh.j2
      dest: "/home/{{ username }}/Programs/ladder/ladder_systray_start.sh"

- name: Copy config files (root)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  loop:
    - src: conky.conf
      dest: /etc/conky/conky.conf
    - src: xfce4-panel.xml
      dest: /etc/xdg/xfce4/panel/default.xml
