- name: Create regular folders
  become_user: "{{ username }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - '/home/{{ username }}/dev'
    - '/home/{{ username }}/Programs'
    - '/home/{{ username }}/.local/share/applications'

- name: Delete unused default folders
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - '/home/{{ username }}/Music'
    - '/home/{{ username }}/Public'
    - '/home/{{ username }}/Templates'
    - '/home/{{ username }}/Videos'
