- name: Create regular folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '660'
  loop:
    - '/home/{{ username }}/dev'
    - '/home/{{ username }}/Programs'

- name: Delete unused default folders
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - '/home/{{ username }}/Music'
    - '/home/{{ username }}/Public'
    - '/home/{{ username }}/Templates'
    - '/home/{{ username }}/Videos'
