- name: Generate OpenSSH keypair for GitHub with the default values (4096 bits, rsa)
  openssh_keypair:
    path: "/home/{{ username }}/.ssh/github2"
    owner: "{{ username }}"
    group: "{{ username }}"
