- name: Add kernel parameters to grub - fixes suspend issues
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=off init_on_alloc=0"'

- name: Update grub
  shell: update-grub
