- name: 'libvirt: Add user to group'
  user:
    name: '{{ username }}'
    groups: libvirt
    append: yes

- name: 'libvirt: Start default network on boot'
  virt_net:
    autostart: true
    name: default
