- name: Copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - src: mac-a1502/switch-option-command.desktop
      dest: "/home/{{ username }}/.config/autostart"

- name: 'Macbook Pro: Copy config files (root)'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  loop:
    - src: mac-a1502/90-monitor.conf
      dest: /etc/X11/xorg.conf.d/90-monitor.conf
    - src: mac-a1502/lid_wakeup_disable 
      dest: /lib/systemd/system-sleep/lid_wakeup_disable
    - src: mac-a1502/network_hack_hibernation
      dest: /usr/lib/systemd/system-sleep/network_hack_hibernation
 
- name: 'Macbook Pro: Add GDK_SCALE to /etc/profile'
  lineinfile:
    dest: /etc/profile
    line: "export GDK_SCALE=2"
    insertafter: EOF
