- name: Change default editor to vim (root)
  blockinfile:
    marker: "## {mark} Change default editor"
    path: "/root/.bashrc"
    insertafter: "EOF"
    block: |
      export VISUAL=vim
      export EDITOR="$VISUAL"

- name: Add ls aliases (root)
  blockinfile:
    marker: "## {mark} Add ls aliases"
    path: "/root/.bashrc"
    insertafter: "EOF"
    block: |
      alias la='ls -la'
      alias ll='ls -lh'
      alias cnf='command-not-found'

- name: Change PS1 color (root)
  blockinfile:
    marker: "## {mark} Change PS1 color"
    path: "/root/.bashrc"
    insertafter: "EOF"
    block: |
      PS1="\[\e[01;31m\]$PS1\[\e[00m\]"

