- name: Disable console freeze
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Disable console freeze"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      # disable tmux freeze + ssh fix: https://stackoverflow.com/questions/24623021/getting-stty-standard-input-inappropriate-ioctl-for-device-when-using-scp-thro
      [[ $- == *i* ]] && /usr/bin/stty -ixon

- name: Add /usr/sbin to PATH
  become: true
  become_user: "{{ username }}"
  blockinfile:
    marker: "## {mark} Add /usr/sbin to PATH"
    path: "/home/{{ username }}/.bashrc"
    insertafter: "EOF"
    block: |
      export PATH="$PATH:/usr/sbin"
