- name: 'resolvconf: Install package - this needs to be the last step because network gets sad'
  apt:
    name: resolvconf
    state: latest

- name: 'resolvconf: Set domain search'
  blockinfile:
      path: /etc/resolvconf/resolv.conf.d/tail
      block: |
            search homelab.matuzalemmuller.com
