- name: 'ThinkPad: Add kernel parameters to grub - fixes suspend issues'
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=off init_on_alloc=0"'

- name: 'ThinkPad: Update grub'
  shell: update-grub

- name: 'ThinkPad T460P: Copy config files (root)'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: true
  loop:
    - src: thinkpad/t460p-tlp.conf
      dest: "/etc/tlp.conf"
  when: ansible_product_version is match("ThinkPad T460p")

- name: 'ThinkPad L14 Gen 3: Copy config files (root)'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: true
  loop:
    - src: thinkpad/l14gen3-tlp.conf
      dest: "/etc/tlp.conf"
  when: ansible_product_version is match("ThinkPad L14 Gen 3")

