- name: Comment cdrom entry from /etc/apt/sources.list
  replace:
    dest: /etc/apt/sources.list
    regexp: '^deb cdrom:'
    replace: '#deb cdrom:' 
 
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - vim
      - git
      - firefox-esr
      - wireshark
      - vlc
      - conky
      - tmux
      - evince
      - transmission-gtk
      - obs-studio
      - cheese
      - gparted
      - htop
      - xfce4-whiskermenu-plugin
      - dconf-cli
      - dconf-editor

- import_tasks: chrome.yml
- import_tasks: docker.yml
- import_tasks: dropbox.yml
- import_tasks: vscode.yml

