- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - vim
      - git
      - firefox
      - wireshark
      - vlc
      - conky
      - tmux
      - evince
      - transmission-gtk
      - obs
      - cheese
      - gparted
      - htop

- import_tasks: docker.yml
- import_tasks: dropbox.yml
- import_tasks: vscode.yml

