name: Syntax check
on: [push]
jobs:
  Basic-Test:
    runs-on: ubuntu-22.04
    container:
      image: alpine:3.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install ansible
        run: apk add ansible
      - name: cd to repository
        run: cd setup-workstation/
      - name: Run ansible-playbook --syntax-check
        run: ansible-playbook playbook/setup-workstation.yml --syntax-check
